#!/bin/sh
set -euo pipefail

# Used internally by bwrap-oci to generate more deterministic output
export TEST=1

export TMP_DIR=$(mktemp -p $(pwd) -d -t .tmp.XXXXXXXXXX)

teardown () {
    rm -rf $TMP_DIR
}
trap teardown EXIT

if test "x${REGENERATE_TESTS_DATA-}" != x && test -e $1.command; then
    sh $1.command > $TMP_DIR/new-file
    mv $TMP_DIR/new-file $1
fi

./bwrap-oci -c $1 --dry-run | sed -e "s|/.*/bwrap|bwrap|g" > $TMP_DIR/output

if test "x${REGENERATE_TESTS_DATA-}" != x; then
    cp $TMP_DIR/output $1.expected
    exit 0
fi

diff -Naur $1.expected $TMP_DIR/output
